spring:
  application:
    name: waterloggingbe
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: p@ssw0rd
    url: jdbc:mysql://localhost/waterlogging?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  jackson:
    # 1)如果属性值为null则不返回对应属性
    default-property-inclusion: non_null
    # 2)若属性值为null也要返回属性，则再vo对象中给属性初始值
  http:
    encoding:
      #字符集设置 解决中文乱码方案
      charset: UTF-8
      force: true
      enabled: true
server:
  port: 5050
  servlet:
    context-path: /api
logging:
  # log配置文件名称
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug
config:
  uploadPath: /upload   #上传文件路径
  downloadUrlPrefix: http://192.168.137.1:5050/api/file/download/  #下载相对路径



